### ISSUE TITLE
RuntimeError: No shared folder available

### ISSUE THREAD

**Issue by pawopawo** [facebookincubator/submitit#1595]
Traceback (most recent call last):
  File "run_with_submitit.py", line 130, in <module>
    main()
  File "run_with_submitit.py", line 89, in main
    args.job_dir = get_shared_folder() / "%j"
  File "run_with_submitit.py", line 40, in get_shared_folder
    raise RuntimeError("No shared folder available")
RuntimeError: No shared folder available

**Comment by gwenzek** [comment]
Hi, this doesn't look like a bug in submitit.
I don't see any submitit code in your callstack, but only the calling code "run_with_submitit.py".
