### ISSUE TITLE
ValueError: LocalExecutor can use only one node. Use nodes=1

### ISSUE THREAD

**Issue by pawopawo** [facebookincubator/submitit#1597]
Traceback (most recent call last):
  File "run_with_submitit.py", line 131, in <module>
    main()
  File "run_with_submitit.py", line 116, in main
    **kwargs
  File "/opt/tiger/conda/lib/python3.7/site-packages/submitit/core/core.py", line 638, in update_parameters
    self._internal_update_parameters(**kwargs)
  File "/opt/tiger/conda/lib/python3.7/site-packages/submitit/auto/auto.py", line 197, in _internal_update_parameters
    self._executor._internal_update_parameters(**parameters)
  File "/opt/tiger/conda/lib/python3.7/site-packages/submitit/local/local.py", line 158, in _internal_update_parameters
    raise ValueError("LocalExecutor can use only one node. Use nodes=1")
ValueError: LocalExecutor can use only one node. Use nodes=1

**Comment by gwenzek** [comment]
Hi, I believe you're new to Github.
You can't just post issues with only a stack trace.
You need to explain what you want to do and why the solution that __you copied in the title__ doesn't work for you.
If you have specific questions, first try to read the documentation, and then if it's not covered, or you're unsure, please ask the question and add details on what is your current understanding.

**Comment by FHL1998** [comment]
I encountered the same issue, have you solved it?
