### ISSUE TITLE
[Bug] Submitit crashes when executor folder contains `\=0` or `"=0"`

### ISSUE THREAD

**Issue by shubham-goel** [facebookincubator/submitit#1600]
Submitit fails then the log directory (folder passed to executor) are of particular form. Examples of logdir that cause this error, but are valid directory names: 
- `logdir = 'submitit_outputs/a"=0"/%j'`
- `logdir = 'submitit_outputs/a\=0/%j'`
- `logdir = 'submitit_outputs/a\=/%j'`

submitit_test.py
```python
import submitit

def add(a, b):
    return a + b

logdir = 'submitit_outputs/a"=0"/%j'
executor = submitit.AutoExecutor(folder=logdir)
executor.update_parameters(timeout_min=4, slurm_partition="priority", slurm_comment='iccv')

job = executor.submit(add, 5, 7)  # will compute add(5, 7)
print(logdir, job.job_id)  # ID of your job

output = job.result()  # waits for the submitted function to complete and returns its output
# if ever the job failed, job.result() will raise an error with the corresponding trace
assert output == 12  # 5 + 7 = 12...  your addition was computed in the cluster
```

Output
```
$ python submitit_test.py 
submitit_outputs/a"=0"/%j 35101624
Traceback (most recent call last):
  File "submitit_test.py", line 13, in <module>
    output = job.result()  # waits for the submitted function to complete and returns its output
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/submitit/core/core.py", line 266, in result
    r = self.results()
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/submitit/core/core.py", line 289, in results
    outcome, result = self._get_outcome_and_result()
  File "/private/home/shubhamgoel/.conda/envs/py3d-implicit/lib/python3.8/site-packages/submitit/core/core.py", line 368, in _get_outcome_and_result
    raise utils.UncompletedJobError(
submitit.core.utils.UncompletedJobError: Job 35101624 (task: 0) with path /private/home/shubhamgoel/code/3Dify/hydra_test/submitit_outputs/a"=0"/35101624/35101624_0_result.pkl
has not produced any output (state: FAILED)
Error stream produced:
----------------------
None
```

**Environment**
submitit 1.1.5
Python 3.8.5
Ubuntu 20.04.1 LTS

**Comment by gwenzek** [comment]
This should be fixed by #1602. Thanks for reporting.

Released in https://pypi.org/project/submitit/1.2.0/
