### ISSUE TITLE
Getting a recursion error with pickling the function

### ISSUE THREAD

**Issue by sgbaird** [facebookincubator/submitit#1636]
```python
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 639, in reducer_override
    if sys.version_info[:2] < (3, 7) and _is_parametrized_type_hint(obj):  # noqa  # pragma: no branch
RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "submit_epdo.py", line 79, in <module>
    jobs = executor.map_array(density_hkl, pars)  # sbatch array
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/submitit/core/core.py", line 630, in map_array
    return self._internal_process_submissions(submissions)
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/submitit/auto/auto.py", line 204, in _internal_process_submissions
    return self._executor._internal_process_submissions(delayed_submissions)
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/submitit/slurm/slurm.py", line 322, in _internal_process_submissions
    d.dump(pickle_path)
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/submitit/core/utils.py", line 134, in dump
    cloudpickle_dump(self, filepath)
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/submitit/core/utils.py", line 238, in cloudpickle_dump
    cloudpickle.dump(obj, ofile, pickle.HIGHEST_PROTOCOL)
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 55, in dump
    CloudPickler(
  File "/uufs/chpc.utah.edu/common/home/u1326059/software/pkg/miniconda3/envs/epdo/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 570, in dump
    raise pickle.PicklingError(msg) from e
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
```
The function uses a `with` statement, the Wolfram Client Library for Python, and a custom package I wrote in Mathematica which I'm using a function from. I imagine pickling the function is what's causing the recursion depth.. If I submit it as a command, does it still pickle the function?

**Comment by sgbaird** [comment]
swapping out the `with` statement doesn't seem to affect it

**Comment by jrapin** [comment]
> I imagine pickling the function is what's causing the recursion depth.. If I submit it as a command, does it still pickle the function?

Yes. This is related to `cloudpickle` more than `submitit`. Not all objects are easy to pickle, `cloudpickle` is already much better than the standard library's `pickle`, but still can't work with everything :s 

> `def wl_test()`

is that the function that you send through `executor.submit`?  since it's stateless it should not cause any issue.

> Is there a way to get submitit to not pickle the function, but just execute the code at runtime? (I realize this doesn't preserve the state of the function at the time of submission)

Not sure I understand what you want here. Pickling just provides the path to the function, or creates a copy of the code for some inline function, the code is only executed at runtime within the job. A few things to consider:
- inline functions are harder to pickle than imported functions, so consider importing from another module instead of defining it in a script.
- you can use `submitit.helpers.CommandFunction` to run a commandline as if it were a function. It's a bit hacky though but it can be handy.

**Comment by sgbaird** [comment]
> is that the function that you send through `executor.submit`?

correct



> * inline functions are harder to pickle than imported functions, so consider importing from another module instead of defining it in a script

Importing from another module was a really helpful tip. Thank you! I think it solved this issue and IIRC another that I ran into later on with `RecursiveDotDict`. Related: https://github.com/materialsproject/matbench/issues/129
