### ISSUE TITLE
Submitit 1.4 fails due to invalid generic resource specification

### ISSUE THREAD

**Issue by SamNPowers** [facebookincubator/submitit#1657]
When I do "pip install submitit" it installs version 1.4 (which doesn't show up in the github release list?). When I run a simple script that works on version 1.2, I get:

```
Traceback (most recent call last):                                                                                                                                   [0/1833]
  File "submit.py", line 10, in <module>
    job = executor.submit(function)
  File "/private/home/spowers/.conda/envs/venv_conda_init_debug/lib/python3.8/site-packages/submitit/core/core.py", line 663, in submit
    job = self._internal_process_submissions([ds])[0]
  File "/private/home/spowers/.conda/envs/venv_conda_init_debug/lib/python3.8/site-packages/submitit/auto/auto.py", line 218, in _internal_process_submissions
    return self._executor._internal_process_submissions(delayed_submissions)
  File "/private/home/spowers/.conda/envs/venv_conda_init_debug/lib/python3.8/site-packages/submitit/slurm/slurm.py", line 313, in _internal_process_submissions
    return super()._internal_process_submissions(delayed_submissions)
  File "/private/home/spowers/.conda/envs/venv_conda_init_debug/lib/python3.8/site-packages/submitit/core/core.py", line 822, in _internal_process_submissions
    job = self._submit_command(self._submitit_command_str)
  File "/private/home/spowers/.conda/envs/venv_conda_init_debug/lib/python3.8/site-packages/submitit/core/core.py", line 863, in _submit_command
    output = utils.CommandFunction(command_list, verbose=False)()  # explicit errors
  File "/private/home/spowers/.conda/envs/venv_conda_init_debug/lib/python3.8/site-packages/submitit/core/utils.py", line 350, in __call__
    raise FailedJobError(stderr) from subprocess_error
submitit.core.utils.FailedJobError: sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification
```

If helpful I can post the generated shell script. Here's my executor definition:

```
executor = submitit.AutoExecutor(folder="tmp/log_test")
executor.update_parameters(timeout_min=1440, slurm_partition="learnlab,learnfair", slurm_gpus_per_task=1, slurm_cpus_per_task=80, slurm_mem_gb=80)
    
```

Is there a known backwards compatibility issue?

**Comment by gwenzek** [comment]
What is your slurm version ?
In the past we were using --gres to specify the number of GPUs, but recent version of slurm don't support this flag and prefer --gpus-per-task or equivalent.
But you shouldn't see this issue especially since #1637 where --gres shouldn't even appear in your sbatch script since you aren't explicitly using it.

Could you find the corresponding sbatch script generated by submitit ?

**Comment by gwenzek** [comment]
closing since no answer, please reopen if it happens again, and don't forget to include the generated sbatch script.
