### ISSUE TITLE
How to catch timed out array jobs

### ISSUE THREAD

**Issue by lee-jin-gyu96** [facebookincubator/submitit#1775]
Hello, 

I've been submitting Slurm job arrays and retrieving the results with something like the code block below:

```
jobs = []
with executor.batch():
    for arg in whatever:
        job = executor.submit(myfunc, arg)
        jobs.append(job)
outputs = [job.result() for job in jobs]
```

The issue is that an error is raised if any of the subjobs time out:
```
File "[...].py", line 55, in <listcomp>
    outputs = [job.result() for job in jobs]
  File "[...]/submitit/core/core.py", line 266, in result
    r = self.results()
  File "[...]/submitit/core/core.py", line 294, in results
    raise job_exception  # pylint: disable=raising-bad-type
submitit.core.utils.FailedJobError: Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
[...]
  File "[...]/submitit/core/job_environment.py", line 226, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: Job not requeued because: timed-out and not checkpointable.
```

Is it possible to just get a None if a subjob times out?

Would I just have to change `outputs = [job.result() for job in jobs]` to something like
```
results = []
for job in jobs:
    try:
        results.append(job.result())
    except Exception:
        logger.warning([...])
```

**Comment by lee-jin-gyu96** [comment]
I closed this issue because the try-except clause kind of worked, but now I'm wondering if there's a good way to check the reason the subjob failed. 

Is there a way to determine the cause of the failure aside from parsing the message from the exception?

**Comment by lee-jin-gyu96** [comment]
Actually, this should probably be a separate issue: one that focuses on error handling and not arrays/subjobs. I'll review past issues again and open a separate issue if need be. Sorry for the mess :)
