### ISSUE TITLE
Latest release is still using pickle to dump objects.

### ISSUE THREAD

**Issue by omry** [facebookincubator/submitit#35]
Despite 1.1.3 having been released after fc7020884fc2c77676984dd343db025d5a251979 was landed, it does not contain this fix.
must have been some mistake with the release.
can you release an update?

```
~/dev/hydra/examples/tutorials/structured_configs/4_defaults$ python my_app.py hydra/launcher=submitit_local -m
[2020-11-18 20:42:46,360][HYDRA] Submitit 'local' sweep output dir : multirun/2020-11-18/20-42-46
[2020-11-18 20:42:46,361][HYDRA]        #0 : 
Traceback (most recent call last):
  File "/home/omry/dev/hydra/hydra/_internal/utils.py", line 196, in run_and_report
    return func()
  File "/home/omry/dev/hydra/hydra/_internal/utils.py", line 353, in <lambda>
    lambda: hydra.multirun(
  File "/home/omry/dev/hydra/hydra/_internal/hydra.py", line 137, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/home/omry/dev/hydra/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/home/omry/dev/hydra/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 150, in launch
    return [j.results()[0] for j in jobs]
  File "/home/omry/dev/hydra/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 150, in <listcomp>
    return [j.results()[0] for j in jobs]
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages/submitit/core/core.py", line 286, in results
    outcome, result = self._get_outcome_and_result()
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages/submitit/core/core.py", line 365, in _get_outcome_and_result
    raise utils.UncompletedJobError(
submitit.core.utils.UncompletedJobError: Job 32380 (task: 0) with path /home/omry/dev/hydra/examples/tutorials/structured_configs/4_defaults/multirun/2020-11-18/20-42-46/.submitit/32380/32380_0_result.pkl
has not produced any output (state: FINISHED)
Error stream produced:
----------------------
submitit ERROR (2020-11-18 20:42:46,769) - Could not dump error:
Can't pickle <class '__main__.Config'>: attribute lookup Config on __main__ failed

because of A temporary saved file already exists.
submitit ERROR (2020-11-18 20:42:46,769) - Submitted job triggered an exception
Traceback (most recent call last):
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages/submitit/core/submission.py", line 65, in submitit_main
    process_job(args.folder)
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages/submitit/core/submission.py", line 58, in process_job
    raise error
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages/submitit/core/submission.py", line 49, in process_job
    utils.pickle_dump(("success", result), tmppath)
  File "/home/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages/submitit/core/utils.py", line 278, in pickle_dump
    pickle.dump(obj, ofile, pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <class '__main__.Config'>: attribute lookup Config on __main__ failed

~/dev/hydra/examples/tutorials/structured_configs/4_defaults$
```

After pip installing from github:
```
~/dev/hydra/examples/tutorials/structured_configs/4_defaults$ python my_app.py hydra/launcher=submitit_local -m
[2020-11-18 20:43:35,456][HYDRA] Submitit 'local' sweep output dir : multirun/2020-11-18/20-43-35
[2020-11-18 20:43:35,457][HYDRA]        #0 : 
~/dev/hydra/examples/tutorials/structured_configs/4_defaults$
```

**Comment by jrapin** [comment]
@gwenzek I check the release you pushed right after the fix, and indeed it does not include the fix, can we release now?

**Comment by jrapin** [comment]
> @gwenzek I check the release you pushed right after the fix, and indeed it does not include the fix, can we release now?

done, thanks to @gwenzek ;)

**Comment by omry** [comment]
Thanks!

**Comment by gwenzek** [comment]
You're welcome, sorry for the screwup. 
I need to invest in a more automated release process.
