### ISSUE TITLE
NotImplementedError when getting a job result for version 1.1.4

### ISSUE THREAD

**Issue by zaccharieramzi** [facebookincubator/submitit#37]
Hi,

I have been using `submitit` a lot recently to submit my jobs on a SLURM-based HPC. It has been very good to me, allowing me to get rid of an extra API writing, so thanks for this project.

When I installed version 1.1.4, I got an error whose stacktrace is as follows:

```python
Traceback (most recent call last):
  File "three_d.py", line 19, in <module>
    train_eval_grid(
  File "/gpfsdswork/projects/rech/hih/uap69lx/submission-scripts/jean_zay/submitit/general_submissions.py", line 63, in train_eval_grid
    run_ids = [job.result() for job in jobs]
  File "/gpfsdswork/projects/rech/hih/uap69lx/submission-scripts/jean_zay/submitit/general_submissions.py", line 63, in <listcomp>
    run_ids = [job.result() for job in jobs]
  File "/linkhome/rech/gencea10/uap69lx/.conda/envs/dis-mri-recon/lib/python3.8/site-packages/submitit/core/core.py", line 266, in result
    r = self.results()
  File "/linkhome/rech/gencea10/uap69lx/.conda/envs/dis-mri-recon/lib/python3.8/site-packages/submitit/core/core.py", line 284, in results
    self.wait()
  File "/linkhome/rech/gencea10/uap69lx/.conda/envs/dis-mri-recon/lib/python3.8/site-packages/submitit/core/core.py", line 387, in wait
    while not self.done():
  File "/linkhome/rech/gencea10/uap69lx/.conda/envs/dis-mri-recon/lib/python3.8/site-packages/submitit/core/core.py", line 424, in done
    if self.watcher.is_done(self.job_id, mode="force" if force_check else "standard"):
  File "/linkhome/rech/gencea10/uap69lx/.conda/envs/dis-mri-recon/lib/python3.8/site-packages/submitit/core/core.py", line 100, in is_done
    state = self.get_state(job_id, mode=mode)
  File "/linkhome/rech/gencea10/uap69lx/.conda/envs/dis-mri-recon/lib/python3.8/site-packages/submitit/core/core.py", line 53, in get_state
    raise NotImplementedError
NotImplementedError
```

I didn't get the chance to work on a minimal reproducible example yet, but I can tell you that this happens in 1.1.4 and doesn't happen in 1.1.3.
I can point you in the meantime to the failing line in my public code: [here](https://github.com/zaccharieramzi/submission-scripts/blob/master/jean_zay/submitit/general_submissions.py#L63).

**Comment by jrapin** [comment]
That's concerning.
@gwenzek there may be something wrong with the watcher of jobs with batch submissions, I'll try to figure this out

**Comment by jrapin** [comment]
Thanks a lot for pointing out, there was indeed a big issue with AutoExecutor and batch submissions. This should be fix as soon as @gwenzek can review it ;)

Also, very happy that this can be useful for a CosmoStat member, say hello to the team from me ;) :D

**Comment by zaccharieramzi** [comment]
Glad I could be of help!

Re the hello, I sure will!

**Comment by gwenzek** [comment]
https://pypi.org/project/submitit/1.1.5/ is out, let me know if the issue persists.
Thanks @jrapin for the quick fix
